name: Package
on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - 'Example.md'
jobs:
  package:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
      - uses: gradle/actions/setup-gradle@v4
      - run: chmod +x ./gradlew
      - name: package
        run: ./gradlew :compiler:assembleJvmDist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: compiler-zip
          path: compiler/build/distributions/compiler-jvm.zip
      - uses: actions/upload-artifact@v4
        with:
          name: compiler-tar
          path: compiler/build/distributions/compiler-jvm.tar
      - uses: actions/upload-artifact@v4
        with:
          name: kotlin-home
          path: home